#!/bin/bash

DOCKER=$(which docker)
if [ $? != 0 ]; then
  echo "Error: docker not found."
  exit 1
fi
GLIDE=$(which glide)
if [ $? != 0 ]; then
  echo "Error: glide not found."
  exit 1
fi
GO=$(which go)
if [ $? != 0 ]; then
  echo "Error: go not found."
  exit 1
fi

$DOCKER stop postgres_container
$DOCKER run --rm --name postgres_container -p 5432:5432 \
  -e POSTGRES_PASSWORD=password -e POSTGRES_DB=skilldirectory \
  -d postgres && echo "Docker container started."
$GLIDE i 
$GO run demo.go

exit
